{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ingress2acmebotreflector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "ingress2acmebotreflector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ingress2acmebotreflector.serviceAccountName" . }}-role
rules:
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "ingress2acmebotreflector.labels" . | nindent 4 }}
  name: {{ include "ingress2acmebotreflector.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ingress2acmebotreflector.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "ingress2acmebotreflector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}