apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress2acmebotreflector
  namespace: spv-system
  labels:
    app: ingress2acmebotreflector
spec:
  selector:
    matchLabels:
      app: ingress2acmebotreflector
  template:
    metadata:
      labels:
        app: ingress2acmebotreflector
    spec:
      serviceAccountName: controller-manager
      containers:
      - name: ingress2acmebotreflector
        image: spvest/ingress2acmebotreflector:v0.0.13
        env:
          - name: BACKEND
            value: https://keyvault-acme-bot-url.com
          - name: AZURE_AD_CLIENT_ID
            value: 00000000-0000-0000-0000-000000000000
          - name: API_SCOPE
            value: api://keyvault-acme-bot
          - name: DOMAINS
            value: example.com,example2.com
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingress2acmebotreflector
    app.kubernetes.io/part-of: ingress2acmebotreflector
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: spv-system
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingress2acmebotreflector
    app.kubernetes.io/part-of: ingress2acmebotreflector
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding
  namespace: spv-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: spv-system


