apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingress2acmebotreflector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress2acmebotreflector.labels" . | nindent 4 }}
    app: {{ include "ingress2acmebotreflector.fullname" . }}
spec:
  # Number of pod replicas desired, only use if HPA is not defined...
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ required "Specify replicaCount" .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "ingress2acmebotreflector.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ingress2acmebotreflector.selectorLabels" . | nindent 8 }}
        app: {{ include "ingress2acmebotreflector.fullname" . }}
    spec:
      serviceAccountName: {{ include "ingress2acmebotreflector.serviceAccountName" . }}
      containers:
        - name: {{ include "ingress2acmebotreflector.fullname" . }}
          image: {{ .Values.image }}
          env:
            - name: BACKEND
              value: {{ required "Specify Backend URL of ACME bot." .Values.backendURL }}
            - name: AZURE_AD_CLIENT_ID
              value: {{ required "Specify Azure Client ID that ACME bot should use." .Values.azureClientId }}
            - name: API_SCOPE
              value: {{ required "Specify API scope of ACME bot" .Values.apiScope }}
            - name: DOMAINS
              value: {{ required "Specify domains that ACME bot should watch for." .Values.domains }}
            - name: ACMEBOT_REST_API_TIMEOUT
              value: {{ .Values.acmebot_rest_api_timeout }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
