repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: spv-charts
    url: https://charts.spvapi.no

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
- name: akv2k8s
  namespace: akv2k8s
  chart: spv-charts/akv2k8s
  set:
    - name: global.keyVaultAuth
      value: "environment"
