name: Lint and test helmchart

on: pull_request

env:
  EXCLUDED_CHARTS: svai-system # comma-separated

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        shell: bash
        # If there are changes, put a comma separated list of `chart/<chart-name>` as output
        run: |
          changed=$(ct list-changed --config ct.yml)
          if [[ -n "$changed" ]]; then
            changed_charts=$(echo $changed | tr ' ' ',')
            echo "changed_charts=$changed_charts" >> "$GITHUB_OUTPUT"
          fi

      - name: Lint chart
        if: ${{ steps.list-changed.outputs.changed_charts != null }}
        run: ct lint --config ct.yml

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        if: ${{ steps.list-changed.outputs.changed_charts != null }}

      - name: Create Kubernetes Kind cluster
        uses: helm/kind-action@v1.9.0
        if: ${{ steps.list-changed.outputs.changed_charts != null }}

      - name: Install infrastructure in Kubernetes Kind
        uses: helmfile/helmfile-action@v1.9.0
        with:
          helmfile-args: apply
        if: ${{ steps.list-changed.outputs.changed_charts != null }}

      - name: Install Flux in Kubernetes Kind
        run: flux install --components-extra="image-reflector-controller,image-automation-controller"
        if: ${{ steps.list-changed.outputs.changed_charts != null }}

      # Run chart tests for changed charts, excluding svai-system
      - name: Run chart-testing (install)
        run: ct install --config ct.yml  --excluded-charts ${{ env.EXCLUDED_CHARTS }}
        if: ${{ steps.list-changed.outputs.changed_charts != null }}
